name: scan_doc
description: "A new Flutter project."
publish_to: 'none'

version: '1.1.0+1'

environment:
  sdk: '>=3.5.3'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  apphud: ^2.5.4
  dio: ^5.4.3+1
  get_it: ^7.7.0
  intl:
  cached_network_image: ^3.3.1
  gaimon: ^1.3.2
  flutter_native_splash: ^2.4.2
  in_app_review: ^2.0.9
  flutter_gen: ^5.8.0
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.2
  freezed_annotation: ^2.1.0
  oktoast: ^3.4.0
  shared_preferences: ^2.2.2
  mask_text_input_formatter: ^2.9.0
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  talker_dio_logger: ^4.4.1
  talker: ^4.4.1
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.3
  local_auth: ^2.3.0
  pro_image_editor:
    git:
      url: https://github.com/Asl20015/pro_image_editor2.git
  pinput: ^5.0.0
  share_plus: ^10.0.2
  drift: ^2.2.0
  url_launcher:
  json_serializable: ^6.8.0
  sqlite3_flutter_libs: ^0.5.10
  carousel_slider: ^5.0.0
  pull_down_button: ^0.10.2
  flagsmith: ^6.0.0
  cunning_document_scanner: ^1.2.3
  permission_handler: ^11.3.1
  flutter_reorderable_grid_view: ^5.4.0
  flutter_open_app_settings: ^0.1.4
  emoji_picker_flutter: ^3.1.0
  flutter_app_info: ^3.0.3
  flutter_email_sender: ^6.0.3
  flutter_animate: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  drift_dev: ^2.2.0+1

flutter_icons:
  image_path: "assets/logo/logo.png"
  android: true
  remove_alpha_ios: true
  ios: true

flutter_native_splash:
  image: "assets/logo/logo.png"
  color: '#9A55FE'


flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/folders/
    - assets/images/stickers/